export const REGISTO_EXITOSO = "REGISTO_EXITOSO";
export const REGISTO_ERROR = "REGISTO_ERROR";

export const LIMPIAR_ALERTA = "LIMPIAR_ALERTA";

export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO";
export const CERRAR_SESION = "CERRAR_SESION";
